services:
  api:
    build: ./api
    container_name: api
    volumes:
      - ./api:/app
    ports:
      - "4567:4567"

  spa:
    build: ./spa
    container_name: spa
    volumes:
      - ./spa:/app
    ports:
      - "4568:4568"

  db:
    image: postgres
    container_name: database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: my_database
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
