services:
  api:
    build: ./api
    container_name: api
    volumes:
      - ./api:/app
    ports:
      - "4567:4567"
    environment:
      - REDIS_URL=redis://redis:6379/
    depends_on:
      - db
      - redis

  spa:
    build: ./spa
    container_name: spa
    volumes:
      - ./spa:/app
    ports:
      - "4568:4568"

  db:
    image: postgres
    container_name: database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: my_database
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./api/scripts/create_table.sql:/docker-entrypoint-initdb.d/init.sql

  test_db:
    image: postgres
    container_name: test_database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test_database
    ports:
      - "5433:5432"
    volumes:
      - pgtestdata:/var/lib/postgresql/data
      - ./api/scripts/create_table.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis
    container_name: redis

  sidekiq:
    build:
      context: ./api
    container_name: sidekiq
    depends_on:
      - api
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/
    ports: []
    command: [ "sidekiq", "-r", "./lib/csv_import_worker.rb" ]

volumes:
  pgdata:
  pgtestdata:
